# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: controls.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ontrols.proto\",\n\x14\x44roneInfoReqResponse\x12\x14\n\x05nodes\x18\x01 \x03(\x0b\x32\x05.Node\"\x14\n\x12GetAllDroneRequest\"\x1b\n\rDroneStateReq\x12\n\n\x02id\x18\x01 \x01(\t\")\n\x12\x44roneStateResponse\x12\x13\n\x04node\x18\x01 \x01(\x0b\x32\x05.Node\"h\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04posX\x18\x02 \x01(\x02\x12\x0c\n\x04posY\x18\x03 \x01(\x02\x12\x0c\n\x04posZ\x18\x04 \x01(\x02\x12\t\n\x01r\x18\x05 \x01(\x02\x12\t\n\x01g\x18\x06 \x01(\x02\x12\t\n\x01\x62\x18\x07 \x01(\x02\x12\t\n\x01\x61\x18\x08 \x01(\x02\"v\n\x12\x44roneUpdateCommand\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04posx\x18\x02 \x01(\x02\x12\x0c\n\x04posy\x18\x03 \x01(\x02\x12\x0c\n\x04posz\x18\x04 \x01(\x02\x12\t\n\x01r\x18\x05 \x01(\x02\x12\t\n\x01g\x18\x06 \x01(\x02\x12\t\n\x01\x62\x18\x07 \x01(\x02\x12\t\n\x01\x61\x18\x08 \x01(\x02\"&\n\x13\x44roneUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb7\x01\n\x0c\x44roneControl\x12\x38\n\x0b\x44roneUpdate\x12\x13.DroneUpdateCommand\x1a\x14.DroneUpdateResponse\x12:\n\x0cGetDroneInfo\x12\x13.GetAllDroneRequest\x1a\x15.DroneInfoReqResponse\x12\x31\n\nDroneState\x12\x0e.DroneStateReq\x1a\x13.DroneStateResponseb\x06proto3')



_DRONEINFOREQRESPONSE = DESCRIPTOR.message_types_by_name['DroneInfoReqResponse']
_GETALLDRONEREQUEST = DESCRIPTOR.message_types_by_name['GetAllDroneRequest']
_DRONESTATEREQ = DESCRIPTOR.message_types_by_name['DroneStateReq']
_DRONESTATERESPONSE = DESCRIPTOR.message_types_by_name['DroneStateResponse']
_NODE = DESCRIPTOR.message_types_by_name['Node']
_DRONEUPDATECOMMAND = DESCRIPTOR.message_types_by_name['DroneUpdateCommand']
_DRONEUPDATERESPONSE = DESCRIPTOR.message_types_by_name['DroneUpdateResponse']
DroneInfoReqResponse = _reflection.GeneratedProtocolMessageType('DroneInfoReqResponse', (_message.Message,), {
  'DESCRIPTOR' : _DRONEINFOREQRESPONSE,
  '__module__' : 'controls_pb2'
  # @@protoc_insertion_point(class_scope:DroneInfoReqResponse)
  })
_sym_db.RegisterMessage(DroneInfoReqResponse)

GetAllDroneRequest = _reflection.GeneratedProtocolMessageType('GetAllDroneRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALLDRONEREQUEST,
  '__module__' : 'controls_pb2'
  # @@protoc_insertion_point(class_scope:GetAllDroneRequest)
  })
_sym_db.RegisterMessage(GetAllDroneRequest)

DroneStateReq = _reflection.GeneratedProtocolMessageType('DroneStateReq', (_message.Message,), {
  'DESCRIPTOR' : _DRONESTATEREQ,
  '__module__' : 'controls_pb2'
  # @@protoc_insertion_point(class_scope:DroneStateReq)
  })
_sym_db.RegisterMessage(DroneStateReq)

DroneStateResponse = _reflection.GeneratedProtocolMessageType('DroneStateResponse', (_message.Message,), {
  'DESCRIPTOR' : _DRONESTATERESPONSE,
  '__module__' : 'controls_pb2'
  # @@protoc_insertion_point(class_scope:DroneStateResponse)
  })
_sym_db.RegisterMessage(DroneStateResponse)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'controls_pb2'
  # @@protoc_insertion_point(class_scope:Node)
  })
_sym_db.RegisterMessage(Node)

DroneUpdateCommand = _reflection.GeneratedProtocolMessageType('DroneUpdateCommand', (_message.Message,), {
  'DESCRIPTOR' : _DRONEUPDATECOMMAND,
  '__module__' : 'controls_pb2'
  # @@protoc_insertion_point(class_scope:DroneUpdateCommand)
  })
_sym_db.RegisterMessage(DroneUpdateCommand)

DroneUpdateResponse = _reflection.GeneratedProtocolMessageType('DroneUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _DRONEUPDATERESPONSE,
  '__module__' : 'controls_pb2'
  # @@protoc_insertion_point(class_scope:DroneUpdateResponse)
  })
_sym_db.RegisterMessage(DroneUpdateResponse)

_DRONECONTROL = DESCRIPTOR.services_by_name['DroneControl']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DRONEINFOREQRESPONSE._serialized_start=18
  _DRONEINFOREQRESPONSE._serialized_end=62
  _GETALLDRONEREQUEST._serialized_start=64
  _GETALLDRONEREQUEST._serialized_end=84
  _DRONESTATEREQ._serialized_start=86
  _DRONESTATEREQ._serialized_end=113
  _DRONESTATERESPONSE._serialized_start=115
  _DRONESTATERESPONSE._serialized_end=156
  _NODE._serialized_start=158
  _NODE._serialized_end=262
  _DRONEUPDATECOMMAND._serialized_start=264
  _DRONEUPDATECOMMAND._serialized_end=382
  _DRONEUPDATERESPONSE._serialized_start=384
  _DRONEUPDATERESPONSE._serialized_end=422
  _DRONECONTROL._serialized_start=425
  _DRONECONTROL._serialized_end=608
# @@protoc_insertion_point(module_scope)
